Update gki-kernel.yml

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -258,32 +258,32 @@ jobs:
             # git revert -m 1 $(git log --grep="remove devpts hook" --pretty=format:"%h") -n
           fi
 
-      # - name: Apply SUSFS Patches for KernelSU Variants
-      #   run: |
-      #     echo "Changing to configuration directory: $CONFIG..."
-      #     cd "$CONFIG"
+      - name: Apply SUSFS Patches for KernelSU Variants
+        run: |
+          echo "Changing to configuration directory: $CONFIG..."
+          cd "$CONFIG"
 
-      #     echo "Applying SUSFS patches..."
+          echo "Applying SUSFS patches..."
 
-      #     # Copy SUSFS patches
-      #     cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch ./common/
-      #     cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
-      #     cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
+          # Copy SUSFS patches
+          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch ./common/
+          cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
+          cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
 
-      #     if [ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]; then
-      #       echo "Applying SUSFS patches for SukiSU..."
-      #        cd KernelSU
+          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]; then
+            echo "Applying SUSFS patches for SukiSU..."
+             cd KernelSU
             
             
-      #       echo "Applying SukiSU specific SUSFS patch..."
-      #     else
-      #       echo "Invalid KernelSU variant selected!"
-      #       exit 1
-      #     fi
+            echo "Applying SukiSU specific SUSFS patch..."
+          else
+            echo "Invalid KernelSU variant selected!"
+            exit 1
+          fi
 
-      #     # Change to common directory and apply common SUSFS patch
-      #     cd ../common
-      #     patch --fuzz=3 -p1 < 50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch || true
+          # Change to common directory and apply common SUSFS patch
+          cd ../common
+          patch --fuzz=3 -p1 < 50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch || true
 
       - name: Apply New Hooks Patches
         run: |
@@ -296,14 +296,14 @@ jobs:
             patch -p1 -F 3 < scope_min_manual_hooks_v1.6.patch
           fi
 
-      # - name: Apply Hide Stuff Patches
-      #   run: |
-      #     echo "Changing to configuration directory: $CONFIG..."
-      #     cd "$CONFIG/common"
-      #     # Apply additional patch
+      - name: Apply Hide Stuff Patches
+        run: |
+          echo "Changing to configuration directory: $CONFIG..."
+          cd "$CONFIG/common"
+          # Apply additional patch
 
-      #     cp ../../SukiSU_patch/69_hide_stuff.patch ./
-      #     patch -p1 -F 3 < 69_hide_stuff.patch
+          cp ../../SukiSU_patch/69_hide_stuff.patch ./
+          patch -p1 -F 3 < 69_hide_stuff.patch
 
       # - name: 复制源文件&应用LZ4KD&ZSTDN补丁
       #   run: |
